// examples/vue-app/src/components/ProductCard.vue
<template>
    <div class="product-card">
      <img :src="thumbnail" :alt="title" class="thumbnail" />
      <h2 class="title">{{ title }}</h2>
      <p class="price">\${{ price }}</p>
      <p class="description">{{ description }}</p>
    </div>
  </template>
  
  <script lang="ts" setup>
  defineProps<{
    title: string
    price: number
    description: string
    thumbnail: string
  }>()
  </script>
  
  <style scoped>
  .product-card {
    border: 1px solid #eee;
    border-radius: 8px;
    padding: 16px;
    max-width: 300px;
  }
  .thumbnail {
    width: 100%;
    height: 180px;
    object-fit: cover;
    border-radius: 4px;
  }
  .title {
    font-size: 18px;
    margin: 12px 0 4px;
  }
  .price {
    color: #888;
    margin: 4px 0;
  }
  .description {
    font-size: 14px;
    color: #555;
  }
  </style>

// examples/react-app/src/ProductCard.tsx
import React from 'react';

interface ProductCardProps {
  title: string;
  price: number;
  description: string;
  thumbnail: string;
}

const ProductCard: React.FC<ProductCardProps> = ({ title, price, description, thumbnail }) => (
  <div style={{ border: '1px solid #eee', borderRadius: 8, padding: 16, maxWidth: 300 }}>
    <img src={thumbnail} alt={title} style={{ width: '100%', height: 180, objectFit: 'cover', borderRadius: 4 }} />
    <h2 style={{ fontSize: 18, margin: '12px 0 4px' }}>{title}</h2>
    <p style={{ color: '#888', margin: '4px 0' }}>${price}</p>
    <p style={{ fontSize: 14, color: '#555' }}>{description}</p>
  </div>
);

export default ProductCard;
