// examples/react-app/src/App.tsx
// src/App.tsx
import React, { useState, useEffect } from "react";
import { useInView, LazyRender } from "@intersection-observer/react";

function LazyImage({ src, alt }: { src: string; alt?: string }) {
  const { ref, inView } = useInView();
  console.log('inView image', inView)
  return (
    <div ref={ref} style={{ minHeight: 600 }}>
      {inView && <img src={src} alt={alt} width="100%" />}
    </div>
  );
}

function InfiniteList({ loadMore }: { loadMore: () => void }) {
  const { ref, inView } = useInView({
    threshold: 0.5,
  });

  React.useEffect(() => {
    if (inView) {
      loadMore();
    }
  }, [inView]);

  return <div ref={ref} style={{ height: 1 }} />;
}

function AnimatedSection({ children }: { children: React.ReactNode }) {
  const { ref, inView } = useInView({ threshold: 0.2 });
  return (
    <div
      ref={ref}
      style={{ opacity: inView ? 1 : 0, transition: "opacity 0.6s" }}
    >
      {children}
    </div>
  );
}

function App() {
  const [items, setItems] = useState<string[]>([]);
  console.log("3333", 3333);
  const loadMore = () =>
    setItems((prev) => [
      ...prev,
      ...Array(10).fill("Item " + (prev.length + 1)),
    ]);

  useEffect(() => loadMore(), []);

  return (
    <div>
      <h1>React Intersection Observer Sandbox</h1>
      <section>
        <h2>1. Lazy Loading Images</h2>
        <LazyImage src="https://picsum.photos/300/200?random=1" />
        <LazyImage src="https://picsum.photos/300/200?random=2" />
        <LazyImage src="https://picsum.photos/300/200?random=3" />
        <LazyImage src="https://picsum.photos/300/200?random=4" />
      </section>

      {/* <section>
        <h2>2. Infinite Scroll</h2>
        {items.map((item, i) => (
          <div key={i}>{item}</div>
        ))}
        <InfiniteList loadMore={() => loadMore()} />
      </section> */}

      <section>
        <h2>3. Scroll-Based Animations</h2>
        {[...Array(5)].map((_, i) => (
          <AnimatedSection key={i}>
            <div style={{ height: 150, margin: "20px 0", background: "#ccc" }}>
              Animation section {i + 1}
            </div>
          </AnimatedSection>
        ))}
      </section>

      <section>
        <h2>4. Analytics Tracking</h2>
        <LazyRender
          onChange={(inView: boolean) => {
            if (inView) console.log("Tracking element visible:");
          }}
        >
          <div style={{ height: 200, background: "#88c" }}>Track me</div>
        </LazyRender>
      </section>

      <section>
        <h2>5. Conditional Rendering with Render Props</h2>
        <LazyRender>
          {({ inView, ref }) => (
            <div
              ref={ref}
              style={{ height: 150, margin: 10, background: "#faa" }}
            >
              {inView ? "In view → Render content" : "Not in view"}
            </div>
          )}
        </LazyRender>
      </section>

      <section>
        <h2>6. Performance Monitoring</h2>
        <LazyRender
          onChange={(visible) => console.log("Performance inView:", visible)}
        >
          {({ ref }) => (
            <div
              ref={ref}
              style={{ height: 150, margin: 10, background: "#aaf" }}
            >
              Check console for perf logs
            </div>
          )}
        </LazyRender>
      </section>
    </div>
  );
}

export default App;

// examples/vue-app/src/App.vue
<template>
  <div>
    <h1>Vue Intersection Observer Sandbox</h1>

    <!-- 1. Lazy Loading Images -->
    <section>
      <h2>1. Lazy Loading Images</h2>
      <LazyImage src="https://picsum.photos/300/200?random=1" />
      <LazyImage src="https://picsum.photos/300/200?random=2" />
      <LazyImage src="https://picsum.photos/300/200?random=3" />
      <LazyImage src="https://picsum.photos/300/200?random=4" />
    </section>

    <!-- 2. Infinite Scroll -->
    <section>
      <h2>2. Infinite Scroll</h2>
      <div v-for="(item, i) in items" :key="i">{{ item }}</div>
      <InfiniteList :load-more="loadMore" />
    </section>

    <!-- 3. Scroll-Based Animations -->
    <section>
      <h2>3. Scroll-Based Animations</h2>
      <AnimatedSection v-for="n in 5" :key="n">
        <template #default>
          <div style="height: 150px; margin: 20px 0; background: #ccc">
            Animation section {{ n }}
          </div>
        </template>
      </AnimatedSection>
    </section>

    <!-- 4. Analytics Tracking -->
    <section>
      <h2>4. Analytics Tracking</h2>
      <LazyRender :onChange="onTrack">
        <template #default="{ ref }">
          <div ref="ref" style="height: 200px; background: #88c">
            Track me
          </div>
        </template>
      </LazyRender>
    </section>

    <!-- 5. Conditional Rendering with Render Props -->
    <section>
      <h2>5. Conditional Rendering with Render Props</h2>
      <LazyRender>
        <template #default="{ inView, ref }">
          <div ref="ref" style="height: 150px; margin: 10px; background: #faa">
            {{ inView ? "In view → Render content" : "Not in view" }}
          </div>
        </template>
      </LazyRender>
    </section>

    <!-- 6. Performance Monitoring -->
    <section>
      <h2>6. Performance Monitoring</h2>
      <LazyRender :onChange="onPerf">
        <template #default="{ ref }">
          <div ref="ref" style="height: 150px; margin: 10px; background: #aaf">
            Check console for perf logs
          </div>
        </template>
      </LazyRender>
    </section>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { LazyRender } from '@intersection-observer/vue'
import LazyImage from './components/LazyImage.vue'
import InfiniteList from './components/InfiniteList.vue'
import AnimatedSection from './components/AnimatedSection.vue'

const items = ref([])

const loadMore = () => {
  const next = Array.from({ length: 10 }, (_, i) => `Item ${items.value.length + i + 1}`)
  items.value.push(...next)
}

onMounted(loadMore)

const onTrack = (inView) => {
  if (inView) {
    console.log('Tracking element visible:')
  }
}

const onPerf = (inView) => {
  console.log('Performance inView:', inView)
}
</script>
